---
title: "Getting Started"
output: rmarkdown::html_vignette
---

### Installing:
```R
library("devtools")
install_github("primitybio/cellengine-r-toolkit")
```

### First steps
#### Authentication:
It is recommended that you set your password in your
`.Renviron`. You can also pass your password as text, but remember that this is
stored by `R`.
```R
library("cellengine")
authenticate("username", Sys.getenv("CELLENGINE_PASSWORD"))
```

#### Get experiments:

Experiments may be listed from your account, or requested individually by ID or
name.
```R
experiments = getExperiments()
exp1 = experiments[1,]
exp2 = getExperiment("57c4d7d4e69a1e890c4d8d2f")
exp3 = getExperiment(byName("experiment_name"))
```


### Looking up Resources by Name:

Gates, Populations, FcsFiles, and Compensations can all be requested by name.
If you are looking up a resource from a specific experiment, this must be done
with the `byName` function:
```R
experimentId = "57c4d7d4e69a1e890c4d8d2f"
gate = getGate(expermentId, byName("gate_name"))
```

You can also create a per-Experiment lookup object, which may be used to find
resources by name or ID. This makes it convenient to query different types of
resources from a single experiment:
```R
experimentId = "57c4d7d4e69a1e890c4d8d2f"
lookup = createLookup(experimentId)
gate = lookup("gates", "gate_name")
population = lookup("populations", "population_name")
```

Looking up a resource by name requires one extra API call, and thus is slightly slower
than lookup up a resource by ID. However, all by-name lookups are cached for the
duration of the `R` session, so repeated calls of the same object are just as
fast as a request by ID.
