---
title: "Gates"
output: rmarkdown::html_vignette
---

### Gates:
Gates are geometric shapes that define boundaries within which events (cells)
must be contained to be considered part of a population.

Gates may be any one of RectangleGate, PolygonGate, EllipseGate, RangeGate,
QuadrantGate or SplitGate.

Compound gates (quadrant and split) are made up of "sectors." Quadrant gates
have four sectors (upper-right, upper-left, lower-left, lower-right) and split
gates have two sectors (left and right). In addition to the top-level GID (like
simple gates), these gates have model.gids and names lists that specify the GID
and name for each sector, in the order shown above. Populations using compound
gates must reference these sector GIDs; referencing the top-level GID of a
compound gate is meaningless.


### Tailoring gates:
When tailoring a gate to a file, a new gate is created with the same GID as the
original gate, but with an fcsFileId property set to the file to which the gate
is tailored. The update and delete API endpoints accept requests by GID to make
for efficient updates to families of tailored gates.

```R
res = createPolygonGate(experimentId="5dcf4551b2b26508af8e63b7", "FSC-A", "FSC-H", "my gate", c(100, 200, 300), c(100, 200, 100), tailoredPerFile=TRUE)
res2 = createPolygonGate(experimentId="5dcf4551b2b26508af8e63b7", "FSC-A", "FSC-H", "my gate", c(100, 200, 300), c(100, 200, 100), tailoredPerFile=TRUE, fcsFile="Specimen_001_Donor1 24h_001.fcs", gid=res$gate$gid, createPopulation=FALSE)
```
